---
spring:
  profiles: dev
generate:
  filePath:
    ip: /var/ftp/ip
    hostname: /var/ftp/hostname
    originIfcfg: /var/ftp/ifcfg
    newIfcfg: /var/ftp/ifcfg-eth0
---
spring:
  profiles: publish
generate:
  filePath:
    ip: /var/ftp/ip
    hostname: /var/ftp/hostname
    originIfcfg: /var/ftp/ifcfg
    newIfcfg: /var/ftp/ifcfg-eth0
---