---
spring:
  profiles: dev
  application:
    name: pcms-midware
eureka:
  client:
    service-url:
      defaultZone: http://10.0.0.9:8761/eureka/
  instance:
    prefer-ip-address: true
---
spring:
  profiles: publish
  application:
    name: pcms-midware
eureka:
  client:
    service-url:
      defaultZone: http://10.0.0.9:8761/eureka/
  instance:
    prefer-ip-address: true
---