---
spring:
  profiles: dev
kvm:
  binPath: /opt/kvm/bin/kvm.sh
  cmd:
    install: install
    restart: restart
    delete: delete
---
spring:
  profiles: publish
kvm:
  binPath: /opt/kvm/bin/kvm.sh
  cmd:
    install: install
    restart: restart
    delete: delete
---
