---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pcms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform:
---
spring:
  profiles: publish
  datasource:
    url: jdbc:mysql://10.0.0.10:3306/pcms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
---